<?php

use Illuminate\Database\Seeder;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('countries')->insert([
            [
                'code' => 'AD',
                'name_en' => 'ANDORRA',
                'name' => 'アンドラ公国',
                'seq' => 0,
                ],
                [
                'code' => 'AE',
                'name_en' => 'UNITED ARAB EMIRATES',
                'name' => 'アラブ首長国連邦',
                'seq' => 0,
                ],
                [
                'code' => 'AF',
                'name_en' => 'AFGHANISTAN',
                'name' => 'アフガニスタン・イスラム国',
                'seq' => 0,
                ],
                [
                'code' => 'AG',
                'name_en' => 'ANTIGUA AND BARBUDA',
                'name' => 'アンチグア・バーブーダ',
                'seq' => 0,
                ],
                [
                'code' => 'AI',
                'name_en' => 'ANGUILLA',
                'name' => 'アンギラ',
                'seq' => 0,
                ],
                [
                'code' => 'AL',
                'name_en' => 'ALBANIA',
                'name' => 'アルバニア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'AM',
                'name_en' => 'ARMENIA',
                'name' => 'アルメニア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'AN',
                'name_en' => 'NETHERLANDS ANTILLES',
                'name' => 'オランダ領アンティル',
                'seq' => 0,
                ],
                [
                'code' => 'AO',
                'name_en' => 'ANGOLA',
                'name' => 'アンゴラ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'AQ',
                'name_en' => 'ANTARCTICA',
                'name' => '南極',
                'seq' => 0,
                ],
                [
                'code' => 'AR',
                'name_en' => 'ARGENTINA',
                'name' => 'アルゼンチン共和国',
                'seq' => 0,
                ],
                [
                'code' => 'AS',
                'name_en' => 'AMERICAN SAMOA',
                'name' => '米領サモア',
                'seq' => 0,
                ],
                [
                'code' => 'AT',
                'name_en' => 'AUSTRIA',
                'name' => 'オーストリア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'AU',
                'name_en' => 'AUSTRALIA',
                'name' => 'オーストラリア',
                'seq' => 0,
                ],
                [
                'code' => 'AW',
                'name_en' => 'ARUBA',
                'name' => 'アルバ',
                'seq' => 0,
                ],
                [
                'code' => 'AX',
                'name_en' => 'ALAND ISLANDS',
                'name' => 'オーランド諸島',
                'seq' => 0,
                ],
                [
                'code' => 'AZ',
                'name_en' => 'AZERBAIJAN',
                'name' => 'アゼルバイジャン共和国',
                'seq' => 0,
                ],
                [
                'code' => 'BA',
                'name_en' => 'BOSNIA AND HERZEGOVINA',
                'name' => 'ボスニア・ヘルツェゴビナ',
                'seq' => 0,
                ],
                [
                'code' => 'BB',
                'name_en' => 'BARBADOS',
                'name' => 'バルバドス',
                'seq' => 0,
                ],
                [
                'code' => 'BD',
                'name_en' => 'BANGLADESH',
                'name' => 'バングラデシュ人民共和国',
                'seq' => 0,
                ],
                [
                'code' => 'BE',
                'name_en' => 'BELGIUM',
                'name' => 'ベルギー王国',
                'seq' => 0,
                ],
                [
                'code' => 'BF',
                'name_en' => 'BURKINA FASO',
                'name' => 'ブルキナファソ',
                'seq' => 0,
                ],
                [
                'code' => 'BG',
                'name_en' => 'BULGARIA',
                'name' => 'ブルガリア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'BH',
                'name_en' => 'BAHRAIN',
                'name' => 'バーレーン王国',
                'seq' => 0,
                ],
                [
                'code' => 'BI',
                'name_en' => 'BURUNDI',
                'name' => 'ブルンジ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'BJ',
                'name_en' => 'BENIN',
                'name' => 'ベナン共和国',
                'seq' => 0,
                ],
                [
                'code' => 'BL',
                'name_en' => 'SAINT BARTHELEMY',
                'name' => 'サン・バルテルミー島',
                'seq' => 0,
                ],
                [
                'code' => 'BM',
                'name_en' => 'BERMUDA',
                'name' => 'バミューダ諸島',
                'seq' => 0,
                ],
                [
                'code' => 'BN',
                'name_en' => 'BRUNEI DARUSSALAM',
                'name' => 'ブルネイ・ダルサラーム国',
                'seq' => 0,
                ],
                [
                'code' => 'BO',
                'name_en' => 'BOLIVIA, PLURINATIONAL STATE OF',
                'name' => 'ボリビア多民族国',
                'seq' => 0,
                ],
                [
                'code' => 'BQ',
                'name_en' => 'BRITISH ANTARCTIC TERRITORY',
                'name' => '英領南極地域',
                'seq' => 0,
                ],
                [
                'code' => 'BR',
                'name_en' => 'BRAZIL',
                'name' => 'ブラジル連邦共和国',
                'seq' => 0,
                ],
                [
                'code' => 'BS',
                'name_en' => 'BAHAMAS',
                'name' => 'バハマ国',
                'seq' => 0,
                ],
                [
                'code' => 'BT',
                'name_en' => 'BHUTAN',
                'name' => 'ブータン王国',
                'seq' => 0,
                ],
                [
                'code' => 'BU',
                'name_en' => 'BURMA',
                'name' => 'ビルマ連邦社会主義共和国',
                'seq' => 0,
                ],
                [
                'code' => 'BV',
                'name_en' => 'BOUVET ISLAND',
                'name' => 'ブーベ島',
                'seq' => 0,
                ],
                [
                'code' => 'BW',
                'name_en' => 'BOTSWANA',
                'name' => 'ボツワナ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'BY',
                'name_en' => 'BELARUS',
                'name' => 'ベラルーシ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'BZ',
                'name_en' => 'BELIZE',
                'name' => 'ベリーズ',
                'seq' => 0,
                ],
                [
                'code' => 'CA',
                'name_en' => 'CANADA',
                'name' => 'カナダ',
                'seq' => 0,
                ],
                [
                'code' => 'CC',
                'name_en' => 'COCOS (KEELING) ISLANDS',
                'name' => 'ココス諸島',
                'seq' => 0,
                ],
                [
                'code' => 'CD',
                'name_en' => 'CONGO, DEMOCRATIC REPUBLIC OF THE',
                'name' => 'コンゴ民主共和国',
                'seq' => 0,
                ],
                [
                'code' => 'CF',
                'name_en' => 'CENTRAL AFRICAN REPUBLIC',
                'name' => '中央アフリカ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'CG',
                'name_en' => 'CONGO',
                'name' => 'コンゴ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'CH',
                'name_en' => 'SWITZERLAND',
                'name' => 'スイス連邦',
                'seq' => 0,
                ],
                [
                'code' => 'CI',
                'name_en' => 'COTE D\'IVOIRE',
                'name' => 'コートジボアール共和国',
                'seq' => 0,
                ],
                [
                'code' => 'CK',
                'name_en' => 'COOK ISLANDS',
                'name' => 'クック諸島',
                'seq' => 0,
                ],
                [
                'code' => 'CL',
                'name_en' => 'CHILE',
                'name' => 'チリ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'CM',
                'name_en' => 'CAMEROON',
                'name' => 'カメルーン共和国',
                'seq' => 0,
                ],
                [
                'code' => 'CN',
                'name_en' => 'CHINA',
                'name' => '中華人民共和国',
                'seq' => 0,
                ],
                [
                'code' => 'CO',
                'name_en' => 'COLOMBIA',
                'name' => 'コロンビア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'CR',
                'name_en' => 'COSTA RICA',
                'name' => 'コスタリカ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'CS',
                'name_en' => 'SERBIA AND MONTENEGRO',
                'name' => 'セルビア・モンテネグロ',
                'seq' => 0,
                ],
                [
                'code' => 'CT',
                'name_en' => 'CANTON AND ENDERBURY ISLANDS',
                'name' => 'カントン島・エンダーバリ島',
                'seq' => 0,
                ],
                [
                'code' => 'CU',
                'name_en' => 'CUBA',
                'name' => 'キューバ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'CV',
                'name_en' => 'CAPE VERDE',
                'name' => 'カーボベルデ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'CX',
                'name_en' => 'CHRISTMAS ISLAND',
                'name' => 'クリスマス島',
                'seq' => 0,
                ],
                [
                'code' => 'CY',
                'name_en' => 'CYPRUS',
                'name' => 'キプロス共和国',
                'seq' => 0,
                ],
                [
                'code' => 'CZ',
                'name_en' => 'CZECH REPUBLIC',
                'name' => 'チェコ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'DD',
                'name_en' => 'GERMAN DEMOCRATIC REPUBLIC',
                'name' => 'ドイツ民主共和国',
                'seq' => 0,
                ],
                [
                'code' => 'DE',
                'name_en' => 'GERMANY',
                'name' => 'ドイツ連邦共和国',
                'seq' => 0,
                ],
                [
                'code' => 'DJ',
                'name_en' => 'DJIBOUTI',
                'name' => 'ジブチ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'DK',
                'name_en' => 'DENMARK',
                'name' => 'デンマーク王国',
                'seq' => 0,
                ],
                [
                'code' => 'DM',
                'name_en' => 'DOMINICA',
                'name' => 'ドミニカ国',
                'seq' => 0,
                ],
                [
                'code' => 'DO',
                'name_en' => 'DOMINICAN REPUBLIC',
                'name' => 'ドミニカ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'DY',
                'name_en' => 'DAHOMEY',
                'name' => 'ダホメ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'DZ',
                'name_en' => 'ALGERIA',
                'name' => 'アルジェリア民主人民共和国',
                'seq' => 0,
                ],
                [
                'code' => 'EC',
                'name_en' => 'ECUADOR',
                'name' => 'エクアドル共和国',
                'seq' => 0,
                ],
                [
                'code' => 'EE',
                'name_en' => 'ESTONIA',
                'name' => 'エストニア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'EG',
                'name_en' => 'EGYPT',
                'name' => 'エジプト・アラブ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'EH',
                'name_en' => 'WESTERN SAHARA',
                'name' => '西サハラ',
                'seq' => 0,
                ],
                [
                'code' => 'ER',
                'name_en' => 'ERITREA',
                'name' => 'エリトリア国',
                'seq' => 0,
                ],
                [
                'code' => 'ES',
                'name_en' => 'SPAIN',
                'name' => 'スペイン',
                'seq' => 0,
                ],
                [
                'code' => 'ET',
                'name_en' => 'ETHIOPIA',
                'name' => 'エチオピア連邦民主共和国',
                'seq' => 0,
                ],
                [
                'code' => 'FI',
                'name_en' => 'FINLAND',
                'name' => 'フィンランド共和国',
                'seq' => 0,
                ],
                [
                'code' => 'FJ',
                'name_en' => 'FIJI',
                'name' => 'フィジー諸島共和国',
                'seq' => 0,
                ],
                [
                'code' => 'FK',
                'name_en' => 'FALKLAND ISLANDS(MALVINAS)',
                'name' => 'フォークランド(マルビナス)諸島',
                'seq' => 0,
                ],
                [
                'code' => 'FM',
                'name_en' => 'MICRONESIA, FEDERATED STATES OF',
                'name' => 'ミクロネシア連邦',
                'seq' => 0,
                ],
                [
                'code' => 'FO',
                'name_en' => 'FAROE ISLANDS',
                'name' => 'フェロー諸島',
                'seq' => 0,
                ],
                [
                'code' => 'FQ',
                'name_en' => 'FRENCH SOUTHERN AND ANTARCTIC TERRITORIES',
                'name' => '仏領諸島',
                'seq' => 0,
                ],
                [
                'code' => 'FR	',
                'name_en' => 'FRANCE',
                'name' => 'フランス共和国',
                'seq' => 0,
                ],
                [
                'code' => 'FX',
                'name_en' => 'FRANCE, METROPOLITAN',
                'name' => 'フランス本国',
                'seq' => 0,
                ],
                [
                'code' => 'GA',
                'name_en' => 'GABON',
                'name' => 'ガボン共和国',
                'seq' => 0,
                ],
                [
                'code' => 'GB',
                'name_en' => 'UNITED KINGDOM',
                'name' => 'グレートブリテンおよび北部アイルランド連合王国(英国)',
                'seq' => 0,
                ],
                [
                'code' => 'GD',
                'name_en' => 'GRENADA',
                'name' => 'グレナダ',
                'seq' => 0,
                ],
                [
                'code' => 'GE',
                'name_en' => 'GEORGIA',
                'name' => 'ジョージア',
                'seq' => 0,
                ],
                [
                'code' => 'GF',
                'name_en' => 'FRENCH GUIANA',
                'name' => 'フランス領ギアナ',
                'seq' => 0,
                ],
                [
                'code' => 'GG',
                'name_en' => 'GUERNSEY',
                'name' => 'ガーンジー島',
                'seq' => 0,
                ],
                [
                'code' => 'GH',
                'name_en' => 'GHANA',
                'name' => 'ガーナ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'GI',
                'name_en' => 'GIBRALTAR',
                'name' => 'ジブラルタル',
                'seq' => 0,
                ],
                [
                'code' => 'GL',
                'name_en' => 'GREENLAND',
                'name' => 'グリーンランド',
                'seq' => 0,
                ],
                [
                'code' => 'GM',
                'name_en' => 'GAMBIA',
                'name' => 'ガンビア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'GN',
                'name_en' => 'GUINEA',
                'name' => 'ギニア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'GP',
                'name_en' => 'GUADELOUPE',
                'name' => 'グアドループ島',
                'seq' => 0,
                ],
                [
                'code' => 'GQ',
                'name_en' => 'EQUATORIAL GUINEA',
                'name' => '赤道ギニア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'GR',
                'name_en' => 'GREECE',
                'name' => 'ギリシア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'GS',
                'name_en' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS',
                'name' => '南ジョージア島・南サンドイッチ諸島',
                'seq' => 0,
                ],
                [
                'code' => 'GT',
                'name_en' => 'GUATEMALA',
                'name' => 'グアテマラ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'GU',
                'name_en' => 'GUAM',
                'name' => 'グアム',
                'seq' => 0,
                ],
                [
                'code' => 'GW',
                'name_en' => 'GUINEA-BISSAU',
                'name' => 'ギニアビサウ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'GY',
                'name_en' => 'GUYANA',
                'name' => 'ガイアナ協同共和国',
                'seq' => 0,
                ],
                [
                'code' => 'HK',
                'name_en' => 'HONG KONG',
                'name' => '香港特別行政区(ホンコン)',
                'seq' => 0,
                ],
                [
                'code' => 'HM',
                'name_en' => 'HEARD ISLAND AND MCDONALD ISLANDS',
                'name' => 'ヘアド島・マクドナルド諸島',
                'seq' => 0,
                ],
                [
                'code' => 'HN',
                'name_en' => 'HONDURAS',
                'name' => 'ホンジュラス共和国',
                'seq' => 0,
                ],
                [
                'code' => 'HR',
                'name_en' => 'CROATIA',
                'name' => 'クロアチア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'HT',
                'name_en' => 'HAITI',
                'name' => 'ハイチ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'HU',
                'name_en' => 'HUNGARY',
                'name' => 'ハンガリー共和国',
                'seq' => 0,
                ],
                [
                'code' => 'HV',
                'name_en' => 'UPPER VOLTA',
                'name' => 'オートボルタ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'ID',
                'name_en' => 'INDONESIA',
                'name' => 'インドネシア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'IE',
                'name_en' => 'IRELAND',
                'name' => 'アイルランド',
                'seq' => 0,
                ],
                [
                'code' => 'IL',
                'name_en' => 'ISRAEL',
                'name' => 'イスラエル国',
                'seq' => 0,
                ],
                [
                'code' => 'IM',
                'name_en' => 'ISLE OF MAN',
                'name' => 'マン島',
                'seq' => 0,
                ],
                [
                'code' => 'IN',
                'name_en' => 'INDIA',
                'name' => 'インド',
                'seq' => 0,
                ],
                [
                'code' => 'IO',
                'name_en' => 'BRITISH INDIAN OCEAN TERRITORY',
                'name' => '英領インド洋地域',
                'seq' => 0,
                ],
                [
                'code' => 'IQ',
                'name_en' => 'IRAQ',
                'name' => 'イラク共和国',
                'seq' => 0,
                ],
                [
                'code' => 'IR',
                'name_en' => 'IRAN, ISLAMIC REPUBLIC OF',
                'name' => 'イラン・イスラム共和国',
                'seq' => 0,
                ],
                [
                'code' => 'IS',
                'name_en' => 'ICELAND',
                'name' => 'アイスランド共和国',
                'seq' => 0,
                ],
                [
                'code' => 'IT',
                'name_en' => 'ITALY',
                'name' => 'イタリア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'JE',
                'name_en' => 'JERSEY',
                'name' => 'ジャージー島',
                'seq' => 0,
                ],
                [
                'code' => 'JM',
                'name_en' => 'JAMAICA',
                'name' => 'ジャマイカ',
                'seq' => 0,
                ],
                [
                'code' => 'JO',
                'name_en' => 'JORDAN',
                'name' => 'ヨルダン・ハシミテ王国',
                'seq' => 0,
                ],
                [
                'code' => 'JP',
                'name_en' => 'JAPAN',
                'name' => '日本国',
                'seq' => 0,
                ],
                [
                'code' => 'JT',
                'name_en' => 'JOHNSTON ISLAND',
                'name' => 'ジョンストン島',
                'seq' => 0,
                ],
                [
                'code' => 'KE',
                'name_en' => 'KENYA',
                'name' => 'ケニア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'KG',
                'name_en' => 'KYRGYZSTAN',
                'name' => 'キルギス共和国',
                'seq' => 0,
                ],
                [
                'code' => 'KH',
                'name_en' => 'CAMBODIA',
                'name' => 'カンボジア王国',
                'seq' => 0,
                ],
                [
                'code' => 'KI',
                'name_en' => 'KIRIBATI',
                'name' => 'キリバス共和国',
                'seq' => 0,
                ],
                [
                'code' => 'KM',
                'name_en' => 'COMOROS',
                'name' => 'コモロ連合',
                'seq' => 0,
                ],
                [
                'code' => 'KN',
                'name_en' => 'SAINT KITTS AND NEVIS',
                'name' => 'セントクリストファー・ネイビス',
                'seq' => 0,
                ],
                [
                'code' => 'KP',
                'name_en' => 'KOREA, DEMOCRATIC PEOPLE\'S REPUBLIC OF',
                'name' => '(北朝鮮=朝鮮民主主義人民共和国)',
                'seq' => 0,
                ],
                [
                'code' => 'KR',
                'name_en' => 'KOREA, REPUBLIC OF',
                'name' => '大韓民国',
                'seq' => 0,
                ],
                [
                'code' => 'KW',
                'name_en' => 'KUWAIT',
                'name' => 'クウェート国',
                'seq' => 0,
                ],
                [
                'code' => 'KY',
                'name_en' => 'CAYMAN ISLANDS',
                'name' => 'ケイマン諸島',
                'seq' => 0,
                ],
                [
                'code' => 'KZ',
                'name_en' => 'KAZAKHSTAN',
                'name' => 'カザフスタン共和国',
                'seq' => 0,
                ],
                [
                'code' => 'LA',
                'name_en' => 'LAO PEOPLE\'S DEMOCRATIC REPUBLIC',
                'name' => 'ラオス人民民主共和国',
                'seq' => 0,
                ],
                [
                'code' => 'LB',
                'name_en' => 'LEBANON',
                'name' => 'レバノン共和国',
                'seq' => 0,
                ],
                [
                'code' => 'LC',
                'name_en' => 'SAINT LUCIA',
                'name' => 'セントルシア',
                'seq' => 0,
                ],
                [
                'code' => 'LI',
                'name_en' => 'LIECHTENSTEIN',
                'name' => 'リヒテンシュタイン公国',
                'seq' => 0,
                ],
                [
                'code' => 'LK',
                'name_en' => 'SRI LANKA',
                'name' => 'スリランカ民主社会主義共和国',
                'seq' => 0,
                ],
                [
                'code' => 'LR',
                'name_en' => 'LIBERIA',
                'name' => 'リベリア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'LS',
                'name_en' => 'LESOTHO',
                'name' => 'レソト王国',
                'seq' => 0,
                ],
                [
                'code' => 'LT',
                'name_en' => 'LITHUANIA',
                'name' => 'リトアニア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'LU',
                'name_en' => 'LUXEMBOURG',
                'name' => 'ルクセンブルク大公国',
                'seq' => 0,
                ],
                [
                'code' => 'LV',
                'name_en' => 'LATVIA',
                'name' => 'ラトビア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'LY',
                'name_en' => 'LIBYAN ARAB JAMAHIRIYA',
                'name' => '社会主義人民リビア・アラブ国',
                'seq' => 0,
                ],
                [
                'code' => 'MA',
                'name_en' => 'MOROCCO',
                'name' => 'モロッコ王国',
                'seq' => 0,
                ],
                [
                'code' => 'MC',
                'name_en' => 'MONACO',
                'name' => 'モナコ公国',
                'seq' => 0,
                ],
                [
                'code' => 'MD',
                'name_en' => 'MOLDOVA, REPUBLIC OF',
                'name' => 'モルドバ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'ME',
                'name_en' => 'MONTENEGRO',
                'name' => 'モンテネグロ',
                'seq' => 0,
                ],
                [
                'code' => 'MF',
                'name_en' => 'SAINT MARTIN (FRENCH PART)',
                'name' => 'サン・マルタン島',
                'seq' => 0,
                ],
                [
                'code' => 'MG',
                'name_en' => 'MADAGASCAR',
                'name' => 'マダガスカル共和国',
                'seq' => 0,
                ],
                [
                'code' => 'MH',
                'name_en' => 'MARSHALL ISLANDS',
                'name' => 'マーシャル諸島共和国',
                'seq' => 0,
                ],
                [
                'code' => 'MI',
                'name_en' => 'MIDWAY ISLANDS',
                'name' => 'ミッドウェー諸島',
                'seq' => 0,
                ],
                [
                'code' => 'MK',
                'name_en' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF',
                'name' => 'マケドニア旧ユーゴスラビア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'ML',
                'name_en' => 'MALI',
                'name' => 'マリ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'MM',
                'name_en' => 'MYANMAR',
                'name' => 'ミャンマー連邦',
                'seq' => 0,
                ],
                [
                'code' => 'MN',
                'name_en' => 'MONGOLIA',
                'name' => 'モンゴル国',
                'seq' => 0,
                ],
                [
                'code' => 'MO',
                'name_en' => 'MACAO',
                'name' => 'マカオ(澳門)',
                'seq' => 0,
                ],
                [
                'code' => 'MP',
                'name_en' => 'NORTHERN MARIANA ISLANDS',
                'name' => '北マリアナ諸島',
                'seq' => 0,
                ],
                [
                'code' => 'MQ',
                'name_en' => 'MARTINIQUE',
                'name' => 'マルチニーク島',
                'seq' => 0,
                ],
                [
                'code' => 'MR',
                'name_en' => 'MAURITANIA',
                'name' => 'モーリタニア・イスラム共和国',
                'seq' => 0,
                ],
                [
                'code' => 'MS',
                'name_en' => 'MONTSERRAT',
                'name' => 'モンセラット',
                'seq' => 0,
                ],
                [
                'code' => 'MT',
                'name_en' => 'MALTA',
                'name' => 'マルタ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'MU',
                'name_en' => 'MAURITIUS',
                'name' => 'モーリシャス共和国',
                'seq' => 0,
                ],
                [
                'code' => 'MV',
                'name_en' => 'MALDIVES',
                'name' => 'モルディヴ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'MW',
                'name_en' => 'MALAWI',
                'name' => 'マラウイ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'MX',
                'name_en' => 'MEXICO',
                'name' => 'メキシコ合衆国',
                'seq' => 0,
                ],
                [
                'code' => 'MY',
                'name_en' => 'MALAYSIA',
                'name' => 'マレーシア',
                'seq' => 0,
                ],
                [
                'code' => 'MZ',
                'name_en' => 'MOZAMBIQUE',
                'name' => 'モザンビーク共和国',
                'seq' => 0,
                ],
                [
                'code' => 'NA',
                'name_en' => 'NAMIBIA',
                'name' => 'ナミビア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'NC',
                'name_en' => 'NEW CALEDONIA',
                'name' => 'ニューカレドニア',
                'seq' => 0,
                ],
                [
                'code' => 'NE',
                'name_en' => 'NIGER',
                'name' => 'ニジェール共和国',
                'seq' => 0,
                ],
                [
                'code' => 'NF',
                'name_en' => 'NORFOLK ISLAND',
                'name' => 'ノーフォーク島',
                'seq' => 0,
                ],
                [
                'code' => 'NG',
                'name_en' => 'NIGERIA',
                'name' => 'ナイジェリア連邦共和国',
                'seq' => 0,
                ],
                [
                'code' => 'NH',
                'name_en' => 'NEW HEBRIDES',
                'name' => 'ニューヘブリデス',
                'seq' => 0,
                ],
                [
                'code' => 'NI',
                'name_en' => 'NICARAGUA',
                'name' => 'ニカラグア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'NL',
                'name_en' => 'NETHERLANDS',
                'name' => 'オランダ王国',
                'seq' => 0,
                ],
                [
                'code' => 'NO',
                'name_en' => 'NORWAY',
                'name' => 'ノルウェー王国',
                'seq' => 0,
                ],
                [
                'code' => 'NP',
                'name_en' => 'NEPAL',
                'name' => 'ネパール連邦民主共和国',
                'seq' => 0,
                ],
                [
                'code' => 'NQ',
                'name_en' => 'DRONNING MAUD LAND',
                'name' => 'ドロニング・マウド',
                'seq' => 0,
                ],
                [
                'code' => 'NR',
                'name_en' => 'NAURU',
                'name' => 'ナウル共和国',
                'seq' => 0,
                ],
                [
                'code' => 'NT',
                'name_en' => 'NEUTRAL ZONE',
                'name' => '中立地帯',
                'seq' => 0,
                ],
                [
                'code' => 'NU',
                'name_en' => 'NIUE',
                'name' => 'ニウエ',
                'seq' => 0,
                ],
                [
                'code' => 'NZ',
                'name_en' => 'NEW ZEALAND',
                'name' => 'ニュージーランド',
                'seq' => 0,
                ],
                [
                'code' => 'OM',
                'name_en' => 'OMAN',
                'name' => 'オマーン国',
                'seq' => 0,
                ],
                [
                'code' => 'PA',
                'name_en' => 'PANAMA',
                'name' => 'パナマ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'PC',
                'name_en' => 'PACIFIC ISLANDS(trust territory)',
                'name' => '太平洋諸島信託統治地域',
                'seq' => 0,
                ],
                [
                'code' => 'PE',
                'name_en' => 'PERU',
                'name' => 'ペルー共和国',
                'seq' => 0,
                ],
                [
                'code' => 'PF',
                'name_en' => 'FRENCH POLYNESIA',
                'name' => 'フランス領ポリネシア',
                'seq' => 0,
                ],
                [
                'code' => 'PG',
                'name_en' => 'PAPUA NEW GUINEA',
                'name' => 'パプアニューギニア',
                'seq' => 0,
                ],
                [
                'code' => 'PH',
                'name_en' => 'PHILIPPINES',
                'name' => 'フィリピン共和国',
                'seq' => 0,
                ],
                [
                'code' => 'PK',
                'name_en' => 'PAKISTAN',
                'name' => 'パキスタン・イスラム共和国',
                'seq' => 0,
                ],
                [
                'code' => 'PL',
                'name_en' => 'POLAND',
                'name' => 'ポーランド共和国',
                'seq' => 0,
                ],
                [
                'code' => 'PM',
                'name_en' => 'SAINT PIERRE AND MIQUELON',
                'name' => 'サンピエール島・ミクロン島',
                'seq' => 0,
                ],
                [
                'code' => 'PN',
                'name_en' => 'PITCAIRN',
                'name' => 'ピトケアン島',
                'seq' => 0,
                ],
                [
                'code' => 'PR',
                'name_en' => 'PUERTO RICO',
                'name' => 'プエルトリコ',
                'seq' => 0,
                ],
                [
                'code' => 'PS',
                'name_en' => 'PALESTINIAN TERRITORY, OCCUPIED',
                'name' => 'パレスチナ占領区域',
                'seq' => 0,
                ],
                [
                'code' => 'PT',
                'name_en' => 'PORTUGAL',
                'name' => 'ポルトガル共和国',
                'seq' => 0,
                ],
                [
                'code' => 'PU',
                'name_en' => 'UNITED STATES MISC. PACIFIC ISLANDS',
                'name' => '米領太平洋諸島',
                'seq' => 0,
                ],
                [
                'code' => 'PW',
                'name_en' => 'PALAU',
                'name' => 'パラオ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'PY',
                'name_en' => 'PARAGUAY',
                'name' => 'パラグアイ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'QA',
                'name_en' => 'QATAR',
                'name' => 'カタール国',
                'seq' => 0,
                ],
                [
                'code' => 'RE',
                'name_en' => 'REUNION',
                'name' => 'レユニオン',
                'seq' => 0,
                ],
                [
                'code' => 'RH',
                'name_en' => 'SOUTHERN RHODESIA',
                'name' => '南ローデシア',
                'seq' => 0,
                ],
                [
                'code' => 'RO',
                'name_en' => 'ROMANIA',
                'name' => 'ルーマニア',
                'seq' => 0,
                ],
                [
                'code' => 'RS',
                'name_en' => 'SERBIA',
                'name' => 'セルビア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'RU',
                'name_en' => 'RUSSIAN FEDERATION',
                'name' => 'ロシア連邦',
                'seq' => 0,
                ],
                [
                'code' => 'RW',
                'name_en' => 'RWANDA',
                'name' => 'ルワンダ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'SA',
                'name_en' => 'SAUDI ARABIA',
                'name' => 'サウジアラビア王国',
                'seq' => 0,
                ],
                [
                'code' => 'SB',
                'name_en' => 'SOLOMON ISLANDS',
                'name' => 'ソロモン諸島',
                'seq' => 0,
                ],
                [
                'code' => 'SC',
                'name_en' => 'SEYCHELLES',
                'name' => 'セイシェル共和国',
                'seq' => 0,
                ],
                [
                'code' => 'SD',
                'name_en' => 'SUDAN',
                'name' => 'スーダン共和国',
                'seq' => 0,
                ],
                [
                'code' => 'SE',
                'name_en' => 'SWEDEN',
                'name' => 'スウェーデン王国',
                'seq' => 0,
                ],
                [
                'code' => 'SG',
                'name_en' => 'SINGAPORE',
                'name' => 'シンガポール共和国',
                'seq' => 0,
                ],
                [
                'code' => 'SH',
                'name_en' => 'SAINT HELENA',
                'name' => 'セントヘレナ島',
                'seq' => 0,
                ],
                [
                'code' => 'SI',
                'name_en' => 'SLOVENIA',
                'name' => 'スロベニア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'SJ',
                'name_en' => 'SVALBARD AND JAN MAYEN',
                'name' => 'スバールバル諸島・ヤンマイエン島',
                'seq' => 0,
                ],
                [
                'code' => 'SK',
                'name_en' => 'SLOVAKIA',
                'name' => 'スロバキア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'SL',
                'name_en' => 'SIERRA LEONE',
                'name' => 'シエラレオネ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'SM',
                'name_en' => 'SAN MARINO',
                'name' => 'サンマリノ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'SN',
                'name_en' => 'SENEGAL',
                'name' => 'セネガル共和国',
                'seq' => 0,
                ],
                [
                'code' => 'SO',
                'name_en' => 'SOMALIA',
                'name' => 'ソマリア民主共和国',
                'seq' => 0,
                ],
                [
                'code' => 'SR',
                'name_en' => 'SURINAME',
                'name' => 'スリナム共和国',
                'seq' => 0,
                ],
                [
                'code' => 'ST',
                'name_en' => 'SAO TOME AND PRINCIPE',
                'name' => 'サントメ・プリンシペ民主共和国',
                'seq' => 0,
                ],
                [
                'code' => 'SU',
                'name_en' => 'USSR',
                'name' => 'ソビエト社会主義共和国連邦',
                'seq' => 0,
                ],
                [
                'code' => 'SV',
                'name_en' => 'EL SALVADOR',
                'name' => 'エルサルバドル共和国',
                'seq' => 0,
                ],
                [
                'code' => 'SY',
                'name_en' => 'SYRIAN ARAB REPUBLIC',
                'name' => 'シリア・アラブ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'SZ',
                'name_en' => 'SWAZILAND',
                'name' => 'スワジランド王国',
                'seq' => 0,
                ],
                [
                'code' => 'TC',
                'name_en' => 'TURKS AND CAICOS ISLANDS',
                'name' => 'タークス諸島・カイコス諸島',
                'seq' => 0,
                ],
                [
                'code' => 'TD',
                'name_en' => 'CHAD',
                'name' => 'チャド共和国',
                'seq' => 0,
                ],
                [
                'code' => 'TF',
                'name_en' => 'FRENCH SOUTHERN TERRITORIES',
                'name' => 'フランス領極南諸島',
                'seq' => 0,
                ],
                [
                'code' => 'TG',
                'name_en' => 'TOGO',
                'name' => 'トーゴ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'TH',
                'name_en' => 'THAILAND',
                'name' => 'タイ王国',
                'seq' => 0,
                ],
                [
                'code' => 'TJ',
                'name_en' => 'TAJIKISTAN',
                'name' => 'タジキスタン共和国',
                'seq' => 0,
                ],
                [
                'code' => 'TK',
                'name_en' => 'TOKELAU',
                'name' => 'トケラウ諸島',
                'seq' => 0,
                ],
                [
                'code' => 'TL',
                'name_en' => 'TIMOR-LESTE',
                'name' => '東ティモール民主共和国',
                'seq' => 0,
                ],
                [
                'code' => 'TM',
                'name_en' => 'TURKMENISTAN',
                'name' => 'トルクメニスタン',
                'seq' => 0,
                ],
                [
                'code' => 'TN',
                'name_en' => 'TUNISIA',
                'name' => 'チュニジア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'TO',
                'name_en' => 'TONGA',
                'name' => 'トンガ王国',
                'seq' => 0,
                ],
                [
                'code' => 'TP',
                'name_en' => 'EAST TIMOR',
                'name' => '東ティモール',
                'seq' => 0,
                ],
                [
                'code' => 'TR',
                'name_en' => 'TURKEY',
                'name' => 'トルコ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'TT',
                'name_en' => 'TRINIDAD AND TOBAGO',
                'name' => 'トリニダード・トバゴ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'TV',
                'name_en' => 'TUVALU',
                'name' => 'ツバル',
                'seq' => 0,
                ],
                [
                'code' => 'TW',
                'name_en' => 'TAIWAN, PROVINCE OF CHINA',
                'name' => 'タイワン(台湾)',
                'seq' => 0,
                ],
                [
                'code' => 'TZ',
                'name_en' => 'TANZANIA, UNITED REPUBLIC OF',
                'name' => 'タンザニア連合共和国',
                'seq' => 0,
                ],
                [
                'code' => 'UA',
                'name_en' => 'UKRAINE',
                'name' => 'ウクライナ',
                'seq' => 0,
                ],
                [
                'code' => 'UG',
                'name_en' => 'UGANDA',
                'name' => 'ウガンダ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'UM',
                'name_en' => 'UNITED STATES MINOR OUTLYING ISLANDS',
                'name' => '米領太平洋諸島',
                'seq' => 0,
                ],
                [
                'code' => 'US',
                'name_en' => 'UNITED STATES',
                'name' => 'アメリカ合衆国(米国)',
                'seq' => 0,
                ],
                [
                'code' => 'UY',
                'name_en' => 'URUGUAY',
                'name' => 'ウルグアイ東方共和国',
                'seq' => 0,
                ],
                [
                'code' => 'UZ',
                'name_en' => 'UZBEKISTAN',
                'name' => 'ウズベキスタン共和国',
                'seq' => 0,
                ],
                [
                'code' => 'VA',
                'name_en' => 'HOLY SEE (VATICAN CITY STATE)',
                'name' => 'バチカン市国',
                'seq' => 0,
                ],
                [
                'code' => 'VC',
                'name_en' => 'SAINT VINCENT AND THE GRENADINES',
                'name' => 'セントビンセントおよびグレナディーン諸島',
                'seq' => 0,
                ],
                [
                'code' => 'VD',
                'name_en' => 'VIETNAM, DEMOCRATIC REPUBLIC OF',
                'name' => 'ベトナム民主共和国',
                'seq' => 0,
                ],
                [
                'code' => 'VE',
                'name_en' => 'VENEZUELA, BOLIVARIAN REPUBLIC OF',
                'name' => 'ベネズエラ・ボリバル共和国',
                'seq' => 0,
                ],
                [
                'code' => 'VG',
                'name_en' => 'VIRGIN ISLANDS, BRITISH',
                'name' => '英領バージン諸島',
                'seq' => 0,
                ],
                [
                'code' => 'VI',
                'name_en' => 'VIRGIN ISLANDS, U.S.',
                'name' => '米領バージン諸島',
                'seq' => 0,
                ],
                [
                'code' => 'VN',
                'name_en' => 'VIET NAM',
                'name' => 'ベトナム社会主義共和国',
                'seq' => 0,
                ],
                [
                'code' => 'VU',
                'name_en' => 'VANUATU',
                'name' => 'バヌアツ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'WF',
                'name_en' => 'WALLIS AND FUTUNA',
                'name' => 'ワリス・フテュナ諸島',
                'seq' => 0,
                ],
                [
                'code' => 'WK',
                'name_en' => 'WAKE ISLAND',
                'name' => 'ウェーク島',
                'seq' => 0,
                ],
                [
                'code' => 'WS',
                'name_en' => 'SAMOA',
                'name' => 'サモア独立国',
                'seq' => 0,
                ],
                [
                'code' => 'XX',
                'name_en' => 'NO PLACE, UNKNOWN, OR UNDETERMINED',
                'name' => '出版地不明',
                'seq' => 0,
                ],
                [
                'code' => 'YD',
                'name_en' => 'YEMEN, DEMOCRATIC',
                'name' => 'イエメン民主人民共和国',
                'seq' => 0,
                ],
                [
                'code' => 'YE',
                'name_en' => 'YEMEN',
                'name' => 'イエメン共和国',
                'seq' => 0,
                ],
                [
                'code' => 'YT',
                'name_en' => 'MAYOTTE',
                'name' => 'マイヨット島',
                'seq' => 0,
                ],
                [
                'code' => 'YU',
                'name_en' => 'YUGOSLAVIA',
                'name' => 'ユーゴスラビア連邦共和国',
                'seq' => 0,
                ],
                [
                'code' => 'ZA',
                'name_en' => 'SOUTH AFRICA',
                'name' => '南アフリカ共和国',
                'seq' => 0,
                ],
                [
                'code' => 'ZM',
                'name_en' => 'ZAMBIA',
                'name' => 'ザンビア共和国',
                'seq' => 0,
                ],
                [
                'code' => 'ZR',
                'name_en' => 'ZAIRE',
                'name' => 'ザイール共和国',
                'seq' => 0,
                ],
                [
                'code' => 'ZW',
                'name_en' => 'ZIMBABWE',
                'name' => 'ジンバブエ共和国',
                'seq' => 0,
                ],
        ]);
    }
}
