#!/bin/bash
rm /var/www/html/appspec.yml
rm -rf /var/www/html/scripts

#.envをS3からコピー
aws s3 cp s3://hakken-develop/asp/.env /var/www/html/.env

mkdir -p /var/www/html/storage/app/tmp


cd /var/www/html

# Install/update composer dependecies
composer install

# メンテナンスモードへ移行（スケジュールタスクも停止になる）
php artisan down

# キャッシュクリア
php artisan cache:clear && php artisan config:clear && php artisan config:cache && php artisan route:clear && php artisan view:clear && php artisan clear-compiled && php artisan optimize && composer dump-autoload && rm -f bootstrap/cache/config.php

# Run database migrations
php artisan migrate --force

#フォルダ・ファイルのパーミッションを変更
chown -R ec2-user:nginx /var/www
chmod 2775 /var/www
find /var/www -type d -exec chmod 2775 {} \;
find /var/www -type f -exec chmod 0664 {} \;

# Turn off maintenance mode
php artisan up

# nginx再起動
systemctl restart php-fpm
systemctl restart nginx